FROM maven
WORKDIR /workspace/app

# build mavem .m2 cache as a layer for reuse
COPY pom.xml pom.xml
RUN mvn dependency:go-offline -B

COPY src src
RUN mvn package -DskipTests

EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "-Xms256m", "-Xmx512m", "target/metadata-service.jar" ]
